server:
  port: 8080

#默认使用配置
mybatis:
  typeAliasesPackage: com.vamrtyv.demo.entity
  mapperLocations: classpath:mapper/*.xml

#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver